name: Fail Fast Demo

on:
    workflow_dispatch:

jobs:
  fail-fast-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1 

    steps:
      - name: Step 1 - Success
        run: | 
            echo "Step 1 passed"
            sleep 80

      - name: Step 2 - Fail intentionally
        run: exit 1
        continue-on-error: true

      - name: Step 3 - Should not run
        run: echo "This should not execute"