# write comment on every line of code

# This is the name of the workflow
name : First Workflow

# This section defines the event that triggers the workflow
# details that the workflow will run when there is a push to the main branch
on :
    push :
        branches :
            - main

# This section defines the jobs that will be run as part of the workflow

jobs :
    first-job:
        # This specifies the type of runner that will be used to execute the job
        runs-on : ubuntu-latest

        # This section defines the steps that will be executed as part of the job
        steps :
            - name : print mesage 1
              # This step uses the run command to execute a shell command that prints a message to the console
              run : echo "This is my first task"
            
            - name : print another message 2
              # This step also uses the run command to execute a shell command that prints another message to the console
              run : echo "This is my second task"
    
    second-job:
        # This specifies the type of runner that will be used to execute the job
        runs-on : ubuntu-latest

        # This section defines the steps that will be executed as part of the job
        steps :
            - name : print mesage 3
              # This step uses the run command to execute a shell command that prints a message to the console
              run : echo "This is my third task"
            
            - name : print another message 4
              # This step also uses the run command to execute a shell command that prints another message to the console
              run : echo "This is my fourth task"


