name : GitHub Hosted Runner Demo

on : workflow_dispatch

jobs :
    linux-job :
        runs-on : ubuntu-latest

        steps :
            - name : Run a script
              run : |
                echo "This is a Linux runner"
                uname -a
                python --version

    windows-job :
        runs-on : windows-latest
        
        steps :
            - name : Run a script
              run : |
                echo "This is a Windows runner"
                systeminfo
                python --version

    macos-job :
        runs-on : macos-latest

        steps :
            - name : Run a script
              run : |
                echo "This is a macOS runner"
                sw_vers
                python --version
        