name: Job Dependencies Demo

on: 
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
            exit 1 
            echo "Building the application"

  test:
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests"

  deploy:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Deploying application"