name : Shell Commands Demo

on :
    workflow_dispatch :

jobs :
    shell-commands-job :
        runs-on : ubuntu-latest

        steps :
            - name : Run single Shell command
              run : echo "This is my first task"
            
            - name : Run multiple python command
              run : |
                    python -c "print('This is my second task')"
                    python --version