name : Shell Commands Demo

on :
    workflow_dispatch :

jobs :
    shell-commands-job :
        runs-on : ubuntu-latest

        steps :
            - name : intentional failure
              run : exit 1
              
            - name : Run single Shell command
              run : echo "This is my first task"
            
            